#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVGraph.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rilevazioni")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertData(Data instance);
    partial void UpdateData(Data instance);
    partial void DeleteData(Data instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CSVGraph.Properties.Settings.Default.RilevazioniConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Data> Data
		{
			get
			{
				return this.GetTable<Data>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data")]
	public partial class Data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _VarName;
		
		private string _TimeString;
		
		private double _VarValue;
		
		private double _VarPosition;
		
		private bool _Validity;
		
		private double _Time_ms;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVarNameChanging(string value);
    partial void OnVarNameChanged();
    partial void OnTimeStringChanging(string value);
    partial void OnTimeStringChanged();
    partial void OnVarValueChanging(double value);
    partial void OnVarValueChanged();
    partial void OnVarPositionChanging(double value);
    partial void OnVarPositionChanged();
    partial void OnValidityChanging(bool value);
    partial void OnValidityChanged();
    partial void OnTime_msChanging(double value);
    partial void OnTime_msChanged();
    #endregion
		
		public Data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string VarName
		{
			get
			{
				return this._VarName;
			}
			set
			{
				if ((this._VarName != value))
				{
					this.OnVarNameChanging(value);
					this.SendPropertyChanging();
					this._VarName = value;
					this.SendPropertyChanged("VarName");
					this.OnVarNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeString", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TimeString
		{
			get
			{
				return this._TimeString;
			}
			set
			{
				if ((this._TimeString != value))
				{
					this.OnTimeStringChanging(value);
					this.SendPropertyChanging();
					this._TimeString = value;
					this.SendPropertyChanged("TimeString");
					this.OnTimeStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarValue", DbType="Float NOT NULL")]
		public double VarValue
		{
			get
			{
				return this._VarValue;
			}
			set
			{
				if ((this._VarValue != value))
				{
					this.OnVarValueChanging(value);
					this.SendPropertyChanging();
					this._VarValue = value;
					this.SendPropertyChanged("VarValue");
					this.OnVarValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarPosition", DbType="Float NOT NULL")]
		public double VarPosition
		{
			get
			{
				return this._VarPosition;
			}
			set
			{
				if ((this._VarPosition != value))
				{
					this.OnVarPositionChanging(value);
					this.SendPropertyChanging();
					this._VarPosition = value;
					this.SendPropertyChanged("VarPosition");
					this.OnVarPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validity", DbType="Bit NOT NULL")]
		public bool Validity
		{
			get
			{
				return this._Validity;
			}
			set
			{
				if ((this._Validity != value))
				{
					this.OnValidityChanging(value);
					this.SendPropertyChanging();
					this._Validity = value;
					this.SendPropertyChanged("Validity");
					this.OnValidityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_ms", DbType="Float NOT NULL")]
		public double Time_ms
		{
			get
			{
				return this._Time_ms;
			}
			set
			{
				if ((this._Time_ms != value))
				{
					this.OnTime_msChanging(value);
					this.SendPropertyChanging();
					this._Time_ms = value;
					this.SendPropertyChanged("Time_ms");
					this.OnTime_msChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
